title: DavitTec
domain: davittec.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://davittec.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: ""  # place folder name if the site is served in a subfolder
timezone: Europe/Berlin
markdown: kramdown

email: info@davit.ie
description:
  A basic Website of DavitTec using Gems jekyll and github_username
  minima.You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

twitter_username: _davit
github_username:  DavitTec

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap 
  - jekyll-seo-tag
#remote_theme: pages-themes/minimal@v0.2.0

include:
  - ".htaccess"
  - _redirects
  - _pages
collections:
  projects:
    output: true
    permalink: /ourwork/:path/
  aboutus:
    output: true
    permalink: /:path/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - wp-content
  - Makefile
  - config.rb
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - jekyll-theme-minimal.gemspec
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
