title: DavitTec
domain: davittec.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://davittec.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /     # place folder name if the site is served in a subfolder


email: info@davit.ie
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
 
twitter_username: _davit
github_username:  DavitTec

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  
  
